### ISSUE TITLE
how to run NAC-ABE in real NDN network

### ISSUE THREAD

**Issue by kangkang333** [UCLA-IRL/NAC-ABE#17]
hello, now I could run NAC-ABE by DummyClientFace， I want to know how to run NAC-ABE in a real NDN network?
I have installed ndnSIM, but I am confused about modifying DummyClientFace to Face

**Comment by tylerliu** [comment]
Hi, for using it in the real NDN network (nan-cxx + NFD), you can use program in `example` folders as a starting point, as specified in [readme](https://github.com/UCLA-IRL/NAC-ABE#23-run-examples).
