### ISSUE TITLE
how to run NAC-ABE in ndnSIM

### ISSUE THREAD

**Issue by kangkang333** [UCLA-IRL/NAC-ABE#19]

**Comment by tylerliu** [comment]
We do not have support to run NAC-ABE in ndnSIM. You might be able to re-write it to an ndnSIM app since it also uses ndn-cxx for Data encoding, but there is no existing solution.

**Comment by kangkang333** [comment]
Thank you for your reply. I want to put NAC-ABE in a simulated NDN network, can I try mini-ndn？

**Comment by tylerliu** [comment]
Yes.

**Comment by kangkang333** [comment]
If I test NAC-ABE in mini-ndn and have installed mini-ndn, I want to know if I need to modify the code of NAC-ABE.

**Comment by tylerliu** [comment]
Ideally it shouldn't need modifications. Let me know if there is any error.

**Comment by kangkang333** [comment]
Thank you for your kind guidance, I will try it
