### ISSUE TITLE
issue when using make for compilation

### ISSUE THREAD

**Issue by dulalsaurab** [UCLA-IRL/NAC-ABE#21]
Compiling/installing nac-abe using `make` doesn't produce any error, but when linking nac-abe from another library, I get the following error. 

```
/usr/bin/ld.gold: error: cannot find -lnac-abe
collect2: error: ld returned 1 exit status
```
The issue doesn't exist when using `waf`. It is uncertain whether the problem is with my machine or due to missing flag/s in the make file.

**Comment by tianyuan129** [comment]
Does this issue still exist?

**Comment by tianyuan129** [comment]
No response.
