### ISSUE TITLE
Data Freshness Period

### ISSUE THREAD

**Issue by dulalsaurab** [UCLA-IRL/NAC-ABE#7]
The data freshness period and other data-related flags are set internally by the library. For example, in most of the producer data generation functions ([here](https://github.com/UCLA-IRL/NAC-ABE/blob/master/src/producer.cpp)), the Freshness Period is set to 5 seconds (hardcoded). This can be a problem for applications that wants a different freshness period, say more than 5 seconds. Also, there doesn't seem to have a provision to set other data flags unless making changes to the library itself.

**Comment by tylerliu** [comment]
Emmm I feel like if we should find a more general solution on data production parameters.

**Comment by tylerliu** [comment]
Fixed by 9dee85159caa002b66d502127b4bd8f0d0dab141
