### ISSUE TITLE
setMustBeFresh in consumer 

### ISSUE THREAD

**Issue by dulalsaurab** [UCLA-IRL/NAC-ABE#8]
While fetching the data consumer sets [setMustBeFresh flag](https://github.com/UCLA-IRL/NAC-ABE/blob/master/src/consumer.cpp#L78). If the data is stale or has a relatively smaller freshness period, consumers won't be able to fetch the data. Aditionally, in the current implementation, the freshness period (+interest flags) is internally set by the library, thus, the application doesn't control these interest and data flags to make the right adjustment as per the need.

**Comment by tylerliu** [comment]
For this, I wonder if it is better to make a `Consumer::consume` function with Interest as argument instead of data name as argument?
