### ISSUE TITLE
Minor cosmetic issue in cache producer

### ISSUE THREAD

**Issue by dulalsaurab** [UCLA-IRL/NAC-ABE#9]
The return of CacheProducer is [`(key, data)`](https://github.com/UCLA-IRL/NAC-ABE/blob/master/src/cache-producer.cpp#L41) whereas in the producer's base class it is [`(data, key)`](https://github.com/UCLA-IRL/NAC-ABE/blob/master/src/producer.cpp#L82). I think it's good to be consistence.

**Comment by tylerliu** [comment]
Fixed by #12
